import { Animated, useAnimatedValue } from "react-native";

export const newValueImpl = (n) => new Animated.Value(n);
export const newValueXYImpl = (x, y) => new Animated.ValueXY({ x, y });
export const setValueImpl = (v, n) => v.setValue(n);
export const setValueXYImpl = (v, xy) => v.setValue(xy);
export const setOffsetImpl = (v, n) => v.setOffset(n);
export const flattenOffsetImpl = (v) => v.flattenOffset();
export const extractOffsetImpl = (v) => v.extractOffset();
export const stopAnimationImpl = (v) => v.stopAnimation();
export const resetAnimationImpl = (v) => v.resetAnimation();
export const interpolateImpl = (v) => (config) => v.interpolate(config);
export const timingImpl = (v) => (config) => Animated.timing(v, config);
export const springImpl = (v) => (config) => Animated.spring(v, config);
export const decayImpl = (v) => (config) => Animated.decay(v, config);
export const startImpl = (anim) => anim.start();
export const startWithCallbackImpl = (anim, cb) => anim.start(cb);
export const stopImpl = (anim) => anim.stop();
export const resetImpl = (anim) => anim.reset();
export const parallelImpl = (anims) => Animated.parallel(anims);
export const sequenceImpl = (anims) => Animated.sequence(anims);
export const staggerImpl = (time) => (anims) => Animated.stagger(time, anims);
export const delayImpl = (time) => Animated.delay(time);
export const loopImpl = (anim) => (config) => Animated.loop(anim, config);
export const addImpl = (a) => (b) => Animated.add(a, b);
export const subtractImpl = (a) => (b) => Animated.subtract(a, b);
export const multiplyImpl = (a) => (b) => Animated.multiply(a, b);
export const divideImpl = (a) => (b) => Animated.divide(a, b);
export const moduloImpl = (a) => (n) => Animated.modulo(a, n);
export const diffClampImpl = (a) => (min) => (max) => Animated.diffClamp(a, min, max);
export const _animatedViewImpl = Animated.View;
export const _animatedTextImpl = Animated.Text;
export const _animatedImageImpl = Animated.Image;
export const _animatedScrollViewImpl = Animated.ScrollView;
export const useAnimatedValueImpl = (n) => () => useAnimatedValue(n);
